apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudmemo
  namespace: team-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudmemo
  template:
    metadata:
      labels:
        app: cloudmemo
    spec:
      containers:
      - name: cloudmemo
        image: <YOUR_IMAGE>
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: redis
---
apiVersion: v1
kind: Service
metadata:
  name: cloudmemo
  namespace: team-blue
spec:
  ports:
    - port: 5000
  selector:
    app: cloudmemo
