all:
  children:
    master:
      hosts:
        192.168.133.139:
    worker:
      hosts:
        192.168.133.138:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_python_interpreter: /usr/bin/python3

